version: "3.9"


services:
  nginx:
    image: nginx:latest
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - s3
      # - rabbitmq
      # - kafka-ui
      # - mailcatcher
    networks:
      app_network:
        aliases:
          - nginx.lvh.me


networks:
  app_network:
    external: false
