version: "3.9"


x-backend-app-environment: &x-backend-app-environment
  LOG_LEVEL: "DEBUG"
  VERSION: "0.1.0"

x-db-environment: &x-db-environment
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "myAwEsOm3pa55@w0rd"
  POSTGRES_USER: "root"


services:
  backend-app:
    platform: linux/amd64
    build:
      context: .
    volumes:
      - ./django:/app
    environment:
      <<:
        - *x-backend-app-environment
        - *x-db-environment

    command: [ "/wait-for-it.sh", "db:5432", "--", "/start.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - keydb
    networks:
      app_network:
        aliases:
          - backend-app.lvh.me


networks:
  app_network:
    external: false
